# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# testclip.py
# Created on: 2017-09-29 15:50:23.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
asset_buff30_noclip_tif = "asset_buff30_noclip.tif"
fuel_tif = "fuel.tif"
asset_buff30_noclip_Clip = "C:\\Users\\m.ashenfarb\\Documents\\ArcGIS\\Default.gdb\\asset_buff30_noclip_Clip"

# Process: Clip
tempEnvironment0 = arcpy.env.snapRaster
arcpy.env.snapRaster = "K:\\TFS_Fire\\Tools\\Mitigation\\Scratch\\fuel.tif"
arcpy.Clip_management(asset_buff30_noclip_tif, "686040.43860271 4339130.3626 688265.43860271 4341210.3626", asset_buff30_noclip_Clip, fuel_tif, "255", "NONE", "MAINTAIN_EXTENT")
arcpy.env.snapRaster = tempEnvironment0

